[package]
name = "xcf"
version = "0.4.0"
edition = "2021"
authors = ["shivshank"]
description = "A basic standalone GIMP XCF library in Rust."
include = [
    "**/*.rs",
    "Cargo.toml",
]

license = "Unlicense"
readme = "README.md"

keywords = ["gimp"]
repository = "https://github.com/shivshank/xcf-rs"

[dependencies]
derive-error = "0.0.4"
byteorder = "1.4.3"

[dev-dependencies]
sha1 = "0.10"
