name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check formatting
      run: cargo fmt -- --check

  build:
    strategy: 
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    name: Builds project
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Build docs
      run: cargo doc --verbose

    - name: Run tests 
      run: cargo test --verbose